### ISSUE TITLE
Error in scons --accelergy

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [NVlabs/timeloop#63]
Hi,

I am getting the following error while running scons --accelergy. The libconfig++-dev version is 1.4.9. Ubuntu version is 14.04.

src/applications/design-space/../mapper/mapper.hpp:580:39: error: ‘class libconfig::Setting’ has no member named ‘lookup’; did you mean ‘lookupValue’?
     libconfig::Setting& mapper = root.lookup("mapper");
                                       ^~~~~~
                                       lookupValue
scons: *** [build/applications/design-space/main.o] Error 1

Can you guide me regarding this error?

**Comment by angshuman-parashar** [comment]
It seems libconfig 1.4.9 does not support lookup(). Please use 1.5+.
Ubuntu 14.04 is a really old distro and you're likely to run into other problems (with gcc, boost etc.) once you resolve the libconfig issue. It's best to upgrade to a more modern environment.

**Comment by Diksha-Moolchandani** [comment]
Thanks. I thought so because it worked fine in Ubuntu 18 with libconfig 1.5.0
